### ISSUE TITLE
Allow optional parameters to be accepted and passed to the authorities

### ISSUE THREAD

**Issue by dbrower** [samvera/questioning_authority#70]

**Comment by elrayle** [comment]
@dbrower This issue has been open a long while. And much work has happened since it was open. I can see how passing through optional parameters can be useful. As the issue is very stale, it is being closed.  If you continue to have this need, please enter a new issue.  It would be useful to have a use case associated with this request identifying a specific authority for which this is desired.  Thanks for working to improve QA.
