### ISSUE TITLE
Change list query to have the following spec

### ISSUE THREAD

**Issue by dbrower** [samvera/questioning_authority#71]
each term in the list is a hash that conforms to the following specification:
- It must have an ID
- It must have a label
- It may have additional fields, such as URI, and authority name.

**Comment by elrayle** [comment]
@dbrower This issue has been open a long while. And much work has happened since it was open. There are several tests related to validating query results, so it is unclear if you have a specific authority for which the specs would apply.  I am closing this issue. If you continue to have questions or suggestions, please enter a new issue.  Thanks for working to improve QA.
